# Base image
FROM node:20-alpine

# Install pnpm
RUN npm install -g pnpm

# Set workdir
WORKDIR /app

# Copy files
COPY package* ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy all files
COPY . .

# Expose Vite port
# EXPOSE 5173

# Start Vite dev server
CMD ["pnpm", "dev", "--", "--host"]